[truck]
base_rate_per_km = 1.5
rate_per_kg = 0.05
rate_per_m3 = 0.1

[boat]
base_rate_per_km = 1.0
rate_per_kg = 0.02
rate_per_m3 = 0.2

[rail]
base_rate_per_km = 1.2
rate_per_kg = 0.03
rate_per_m3 = 0.15